# -- Stages --

stages:
  - build
  - test
  # - deploy
  - clean

# -- Variables --

variables:
  GIT_DEPTH: 1 # Sets git shallow clone to 1 commit.

# -- Jobs --

# Application building

building:
  stage: build
  only:
    - master # Restricts the building to the master branch.
    - develop # Restricts the building to the develop branch.
  script:
    - echo "--Building--"

    # npm

    - npm install # Installs the dependencies.
    - npm run build # Builds the application.

# Unit testing

unit-testing:
  stage: test
  only:
    - master # Restricts the unit to the master branch.
    - develop # Restricts the unit to the develop branch.
  variables:
    GIT_STRATEGY: none # Skips the 'git fetch'.
  script:
    - echo "--Unit testing--"

    # Cypress

    - npm run test_unit # Starts the unit testing.

# UI unit testing

ui-unit-testing:
  stage: test
  only:
    - master # Restricts the ui unit to the master branch.
    - develop # Restricts the ui unit to the develop branch.
  variables:
    GIT_STRATEGY: none # Skips the 'git fetch'.
  needs: [unit-testing]
  script:
    - echo "--UI init testing--"

    # Cypress

    - npm run test_unit_ui # Starts the ui unit testing.

# UI integration testing

ui-integration-testing:
  stage: test
  only:
    - master # Restricts the ui integration testing to the master branch.
    - develop # Restricts the ui integration testing to the develop branch.
  variables:
    GIT_STRATEGY: none # Skips the 'git fetch'.
  needs: [ui-unit-testing]
  script:
    - echo "--UI integration testing--"

    # Cypress

    - npm run test_integration_ui # Starts the ui integration testing.

# Application deployment

# deploying:
#   image: docker:latest
#   stage: deploy
#   only:
#     - master # Restricts the deployment only for the master branch.
#   services:
#     - docker:dind
#   script:
#     - echo "--Deploying--"
#     - docker build -t <host>:<port>/<image name>:latest
#     - docker push <host>:<port>/<image name>:latest

# Cleaning

cleaning:
  image: docker:latest
  stage: clean
  only:
    - master # Restricts the cleaning to the master branch.
    - develop # Restricts the cleaning to the develop branch.
  variables:
    GIT_STRATEGY: none # Skips the 'git fetch'.
  script:
    - echo "--Cleaning $CI_PROJECT_DIR--"
    - New-Item -ItemType directory -Path ../ -Name "empty" # Creates an empty folder for file deletion.
    - robocopy ../empty ./ /MIR; if ($lastexitcode -lt 8) { $global:LASTEXITCODE = $null } # Removes ALL the source files on the host machine runner.
    - rm ..\empty\
