FROM node:lts-alpine

RUN npm install -g http-server

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG VITE_DOWNLOADING_MICROSERVICE
ARG VITE_REVERSE_ENGINEERING_MICROSERVICE
ARG VITE_VISUALIZING_MICROSERVICE
ARG VITE_EVOLVING_MICROSERVICE

ENV VITE_DOWNLOADING_MICROSERVICE=$VITE_DOWNLOADING_MICROSERVICE
ENV VITE_REVERSE_ENGINEERING_MICROSERVICE=$VITE_REVERSE_ENGINEERING_MICROSERVICE
ENV VITE_VISUALIZING_MICROSERVICE=$VITE_VISUALIZING_MICROSERVICE
ENV VITE_EVOLVING_MICROSERVICE=$VITE_EVOLVING_MICROSERVICE

RUN npm run build

EXPOSE 8080

CMD [ "http-server", "dist" ]